- hosts: localhost
  vars_files:
          - cred.yml
  tasks:
          - name: send email
            mail:
                    host: smtp.gmail.com
                    port: 587
                    username: cankush620@gmail.com
                    password: "{{ emailpass }}"
                    to: cankush630@gmail.com
                    subject: Ansible mail package test
                    body: mail sent by {{ ansible_hostname }}
