---
- hosts: localhost
  vars_files:
          secret.yml
  tasks:
          - name: Provisioning OS on AWS
            ec2:
                    key_name: "cankush625"
                    instance_type: "t2.micro"
                    image: "ami-0ebc1ac48dfd14136"
                    wait: yes
                    count: 1
                    vpc_subnet_id: "subnet-2f0b3147"
                    assign_public_ip: yes
                    region: "ap-south-1"
                    state: present
                    group_id: "sg-0a3cf52af06219e50"
                    instance_tags:
                            Name: "AutoWebConfig"
                    aws_access_key: "{{ aws_access }}"
                    aws_secret_key: "{{ aws_secret }}"
            register: result
            #- name: SSH into aws
            #            command: ssh -l ec2-user -i /home/cankush/Downloads/cankush625.pem {{ result.instances[0].public_ip }} -y



- hosts: all
  roles:
          - role: webserver
            port: 8123
